In [12]:
import numpy as np

# 1. Create an array with 4 rows and 3 columns of zeros.
zeros_array = np.zeros((4, 3))
print("1.", zeros_array)

# 2. Create an array of ones that has 3 rows and 4 columns.
ones_array = np.ones((3, 4))
print("2.", ones_array)

# 3. Create an array containing integers 4 to 13 inclusive.
int_array = np.arange(4, 14)
print("3.", int_array)

# 4. Create an array containing [0., 1.5, 3., 4.5].
float_array = np.arange(0, 6, 1.5)
print("4.", float_array)

# 5. Create a 2 by 2 array containing '4' in each position.
four_array = np.full((2, 2), 4)
print("5.", four_array)

# 6i. Identity matrix of size 4
identity_matrix = np.eye(4)
print("6i.", identity_matrix)

# 6ii. Diagonal matrix with [10,12] as the diagonals
diagonal_matrix = np.diag([10, 12])
print("6ii.", diagonal_matrix)

# 7. Create a 3 by 3 array with random floats in [0, 10].
random_float_array = np.random.uniform(0, 10, (3, 3))
print("7.", random_float_array)

# 8. Create a 3 by 3 array with random integers in [10, 20].
random_int_array = np.random.randint(10, 21, (3, 3))
print("8.", random_int_array)

# Define the array for slicing practice

# Remove the elements from the middle column of this array:

# Extract the first four



1. [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2. [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
3. [ 4  5  6  7  8  9 10 11 12 13]
4. [0.  1.5 3.  4.5]
5. [[4 4]
 [4 4]]
6i. [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
6ii. [[10  0]
 [ 0 12]]
7. [[7.14087183 3.43481233 1.13619012]
 [3.21057843 5.3221662  0.51712673]
 [1.21258004 1.09956625 1.25737649]]
8. [[11 13 17]
 [15 12 11]
 [15 11 19]]


In [13]:
myArray = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
myArray = np.delete(myArray, 1, axis=1)
print(myArray)

# Replace all odd numbers in the given array with -1
exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
exercise_1[exercise_1 % 2 != 0] = -1
print("Test Exercise 1:", exercise_1)

# Convert a 1-D array into a 2-D array with 3 rows
exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
exercise_2 = exercise_2.reshape(3, -1)
print("Test Exercise 2:\n", exercise_2)

# Add 202 to all the values in given array
exercise_3 = np.arange(4).reshape(2, -1)
exercise_3 += 202
print("Test Exercise 3:\n", exercise_3)

# Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive)
random_integers = np.random.randint(30, 41, 10)
print("Test Exercise 4:", random_integers)

# Find the positions of:
# elements in x where its value is more than its corresponding element in y, and
# elements in x where its value is equals to its corresponding element in y.
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
greater_positions = np.where(x > y)
equal_positions = np.where(x == y)
print("Test Exercise 5a:", greater_positions)
print("Test Exercise 5b:", equal_positions)


[[1 3]
 [4 6]
 [9 7]]
Test Exercise 1: [ 0 -1  2 -1  4 -1  6 -1  8 -1]
Test Exercise 2:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Test Exercise 3:
 [[202 203]
 [204 205]]
Test Exercise 4: [32 32 35 38 39 37 39 37 31 34]
Test Exercise 5a: (array([1, 2, 4, 5, 6, 7, 8, 9], dtype=int64),)
Test Exercise 5b: (array([0], dtype=int64),)


In [14]:
myArray = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

# a. Get a subarray of the first row and first 2 columns.
sub_array = myArray[:1, :2]
print("a.", sub_array)

# b. Change all elements in 1st and second row to 0.
myArray[:2] = 0
print("b.", myArray)

# Use this array for the following practice:
myArray = np.array([[11, 12, 13], [14, 15, 16]])

# Reshape the array to an array with 3 rows.
reshaped_array = myArray.reshape(3, 2)
print("Reshaped Array:", reshaped_array)

# Use this array for the following practice:
myArray = np.arange(10)

# 1. Find the square of every number in array
squared_array = np.square(myArray)
print("1. Squared Array:", squared_array)

# 2. Find the square root of every number in array
sqrt_array = np.sqrt(myArray)
print("2. Square Root Array:", sqrt_array)

# 3. Multiply the square of each number in array with its respective square root
result_array = squared_array * sqrt_array
print("3. Result Array:", result_array)

# Use this array for the following practice:
myArray = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

# 1. Add a new row of elements containing 20, 21 and 22
new_row = np.array([20, 21, 22])
myArray = np.vstack([myArray, new_row])
print("1.", myArray)

# 2. Add a new column of elements containing 30, 40 and 50


# 1. Add 1 column of 1 to this array: myArray = np.zeros((2,2))
myArray = np.zeros((2, 2))
myArray = np.insert(myArray, 1, 1, axis=1)
print("1.", myArray)

# 2. Add 2 rows of 2 to the answer from part 1
myArray = np.insert(myArray, 1, 2, axis=0)
print("2.", myArray)

# 3. Remove the last column
myArray = np.delete(myArray, -1, axis=1)
print("3.", myArray)

# 4. Remove the last row
myArray = np.delete(myArray, -1, axis=0)
print("4.", myArray)



a. [[11 12]]
b. [[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]
Reshaped Array: [[11 12]
 [13 14]
 [15 16]]
1. Squared Array: [ 0  1  4  9 16 25 36 49 64 81]
2. Square Root Array: [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
3. Result Array: [  0.           1.           5.65685425  15.58845727  32.
  55.90169944  88.18163074 129.64181424 181.01933598 243.        ]
1. [[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]
1. [[0. 1. 0.]
 [0. 1. 0.]]
2. [[0. 1. 0.]
 [2. 2. 2.]
 [0. 1. 0.]]
3. [[0. 1.]
 [2. 2.]
 [0. 1.]]
4. [[0. 1.]
 [2. 2.]]


In [15]:
new_col = np.array([[30], [40], [50]])
myArray = np.hstack([myArray, new_col])
print("2.", myArray)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3